import { Translations } from './types';

export const translations: Translations = {
    ar: {
        designer: "تصميم : حوامرية نذير",
        mainTitle: "AI Scene Director By Nadir",
        subTitle: "أخرج مشاهدك الخاصة بدمج الشخصيات وتبديلها بواقعية.",
        modeSwap: "تبديل الوجه",
        modeAdd: "إضافة شخصية",
        inputSectionTitle: "1. الصور المدخلة",
        sourceImageTitle: "الصورة الأصلية (المشهد)",
        uploadSceneTitle: "تحميل المشهد الأصلي",
        uploaderSubtitle: "اسحب وأفلت أو انقر للاختيار",
        targetHeadsTitle: "الوجه الجديد (للتبديل)",
        targetHeadTitle: "الوجه",
        newPersonTitle: "الشخصية الجديدة (للإضافة)",
        uploadPersonTitle: "تحميل صورة الشخصية",
        adjustSectionTitle: "2. تعديل أو تصحيح (اختياري)",
        adjustPlaceholder: "مثال: اجعلها تبتسم...",
        addPersonPromptTitle: "2. التحكم في الشخصية المضافة",
        addPersonPromptPlaceholder: "مثال: يقف بجانب السيارة، يرتدي قميصاً أحمر...",
        submitButtonSwap: "توليد الصورة",
        submitButtonAdd: "أضف الشخصية",
        submitButtonLoading: "جاري المعالجة...",
        resultSectionTitle: "النتيجة",
        resultLoadingText: "يقوم الذكاء الاصطناعي بسحره...",
        loadingStatus1: "الخطوة 1/2: تحليل المشهد...",
        loadingStatus2: "الخطوة 2/2: توليد الصورة الجديدة...",
        resultPlaceholderText: "ستظهر صورتك المعدلة هنا",
        resultTip: "نصيحة: للحصول على أفضل النتائج، استخدم صورًا ذات وجوه واضحة وعالية الجودة.",
        downloadButton: "تحميل",
        regenerateButton: "إعادة التوليد",
        errorPrefix: "حدث خطأ",
        errorUploadSwap: "لوضع تبديل الوجه، الرجاء تحميل المشهد وصورة الوجه الجديد.",
        errorUploadAdd: "لوضع الإضافة، الرجاء تحميل المشهد وصورة الشخصية.",
        errorNoImage: "لم يتم العثور على بيانات الصورة في استجابة واجهة برمجة التطبيقات.",
        errorResize: "فشل في معالجة الصورة. الرجاء المحاولة بصورة أخرى.",
    },
    en: {
        designer: "Designed by: Houamria Nadir",
        mainTitle: "AI Scene Director By Nadir",
        subTitle: "Direct your own scenes by adding and swapping characters realistically.",
        modeSwap: "Face Swap",
        modeAdd: "Add Person",
        inputSectionTitle: "1. Input Images",
        sourceImageTitle: "Source Image (Scene)",
        uploadSceneTitle: "Upload Original Scene",
        uploaderSubtitle: "Drag & drop or click to select",
        targetHeadsTitle: "New Face (for Swapping)",
        targetHeadTitle: "Face",
        newPersonTitle: "New Person (for Adding)",
        uploadPersonTitle: "Upload Person's Image",
        adjustSectionTitle: "2. Adjust or Correct (Optional)",
        adjustPlaceholder: "e.g., make them smile...",
        addPersonPromptTitle: "2. Control The Added Person",
        addPersonPromptPlaceholder: "e.g., standing by the car, wearing a red shirt...",
        submitButtonSwap: "Perform Swap",
        submitButtonAdd: "Add Person",
        submitButtonLoading: "Processing...",
        resultSectionTitle: "Result",
        resultLoadingText: "The AI is working its magic...",
        loadingStatus1: "Step 1/2: Analyzing Scene...",
        loadingStatus2: "Step 2/2: Generating New Image...",
        resultPlaceholderText: "Your generated image will appear here",
        resultTip: "Tip: For best results, use images with clear, high-quality faces.",
        downloadButton: "Download",
        regenerateButton: "Regenerate",
        errorPrefix: "An error occurred",
        errorUploadSwap: "For Face Swap Mode, please upload the scene and the new face's image.",
        errorUploadAdd: "For Add Mode, please upload the scene and the person's image.",
        errorNoImage: "No image data found in API response.",
        errorResize: "Failed to process image. Please try another one.",
    },
    fr: {
        designer: "Conçu par : Houamria Nadir",
        mainTitle: "AI Scene Director par Nadir",
        subTitle: "Dirigez vos propres scènes en ajoutant et en échangeant des personnages de manière réaliste.",
        modeSwap: "Échange de Visage",
        modeAdd: "Ajouter Personne",
        inputSectionTitle: "1. Images d'Entrée",
        sourceImageTitle: "Image Source (Scène)",
        uploadSceneTitle: "Télécharger la Scène Originale",
        uploaderSubtitle: "Glissez-déposez ou cliquez pour sélectionner",
        targetHeadsTitle: "Nouveau Visage (à échanger)",
        targetHeadTitle: "Visage",
        newPersonTitle: "Nouvelle Personne (à ajouter)",
        uploadPersonTitle: "Télécharger l'Image de la Personne",
        adjustSectionTitle: "2. Ajuster ou Corriger (Optionnel)",
        adjustPlaceholder: "ex: faites-le sourire...",
        addPersonPromptTitle: "2. Contrôler la Personne Ajoutée",
        addPersonPromptPlaceholder: "ex: debout près de la voiture, portant une chemise rouge...",
        submitButtonSwap: "Effectuer l'Échange",
        submitButtonAdd: "Ajouter Personne",
        submitButtonLoading: "Traitement en cours...",
        resultSectionTitle: "Résultat",
        resultLoadingText: "L'IA opère sa magie...",
        loadingStatus1: "Étape 1/2 : Analyse de la scène...",
        loadingStatus2: "Étape 2/2 : Génération de la nouvelle image...",
        resultPlaceholderText: "Votre image générée apparaîtra ici",
        resultTip: "Conseil : Pour de meilleurs résultats, utilisez des images avec des visages clairs et de haute qualité.",
        downloadButton: "Télécharger",
        regenerateButton: "Régénérer",
        errorPrefix: "Une erreur est survenue",
        errorUploadSwap: "Pour le mode Échange de Visage, veuillez télécharger la scène et l'image du nouveau visage.",
        errorUploadAdd: "Pour le mode Ajout, veuillez télécharger la scène et l'image de la personne.",
        errorNoImage: "Aucune donnée d'image trouvée dans la réponse de l'API.",
        errorResize: "Échec du traitement de l'image. Veuillez en essayer une autre.",
    }
};